// <auto-generated />
using System;
using MeuTeste.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgenciaDeViagens.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20211220160728_Viagens")]
    partial class Viagens
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MeuTeste.Models.Cliente", b =>
                {
                    b.Property<int>("ID_Cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("data_nasc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("telefone")
                        .HasColumnType("int");

                    b.HasKey("ID_Cliente");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("MeuTeste.Models.Viagem", b =>
                {
                    b.Property<int>("ID_Viagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ClienteID_Cliente")
                        .HasColumnType("int");

                    b.Property<DateTime>("data")
                        .HasColumnType("datetime2");

                    b.Property<string>("destino")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("passagem")
                        .HasColumnType("int");

                    b.HasKey("ID_Viagem");

                    b.HasIndex("ClienteID_Cliente");

                    b.ToTable("viagens");
                });

            modelBuilder.Entity("MeuTeste.Models.Viagem", b =>
                {
                    b.HasOne("MeuTeste.Models.Cliente", "Cliente")
                        .WithMany("viagens")
                        .HasForeignKey("ClienteID_Cliente");

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("MeuTeste.Models.Cliente", b =>
                {
                    b.Navigation("viagens");
                });
#pragma warning restore 612, 618
        }
    }
}
